import {
  z,
  idSchema,
  isoDateTimeSchema,
  metadataSchema,
  providerSchema,
  providerConnectionStatusSchema,
  taskTypeSchema,
  prioritySchema,
  auditSourceSchema,
  freeAuditCtaSchema,
  riskLevelSchema,
  modelFitSchema,
  registryFreshnessSchema,
  stabilityStatusSchema,
  latencyTierSchema,
  qualityTierSchema,
  modelRegistryApprovalStateSchema,
  promptStatusSchema,
  candidateStrategySchema,
  evalStatusSchema,
  evalVerdictSchema,
  testCheckTypeSchema,
  reportStatusSchema,
  reportArtifactFormatSchema,
  reportArtifactPrivacyStateSchema,
  artifactDeletionStatusSchema,
  retentionStateSchema,
  deletionRequestStatusSchema,
  adminActionScopeSchema,
  adminRoleNameSchema,
  adminUserStatusSchema,
  sudoRequestStatusSchema,
  redactionStateSchema,
  accountStageSchema,
  opportunityStageSchema,
  evalReadinessSchema,
  entitlementFeatureSchema,
  usageLedgerUnitSchema,
  ledgerDirectionSchema
} from './common';

export const freeAuditSchema = z
  .object({
    id: idSchema,
    account_id: idSchema.nullable(),
    project_id: idSchema.nullable(),
    provider: providerSchema,
    current_model_id: z.string().min(1),
    task_type: taskTypeSchema,
    monthly_calls: z.number().int().positive(),
    model_fit: modelFitSchema,
    savings_opportunity_usd: z.number().nonnegative().nullable(),
    eval_readiness: evalReadinessSchema,
    contact_email: z.string().email().nullable(),
    company: z.string().min(1).nullable(),
    cta_clicked: freeAuditCtaSchema,
    redacted_prompt_preview: z.string().min(1),
    shareable_summary: z.string().min(1),
    is_mock: z.boolean(),
    created_at: isoDateTimeSchema
  })
  .strict();
export type FreeAudit = z.infer<typeof freeAuditSchema>;
