import {
  z,
  idSchema,
  isoDateTimeSchema,
  metadataSchema,
  providerSchema,
  providerConnectionStatusSchema,
  taskTypeSchema,
  prioritySchema,
  auditSourceSchema,
  freeAuditCtaSchema,
  riskLevelSchema,
  modelFitSchema,
  registryFreshnessSchema,
  stabilityStatusSchema,
  latencyTierSchema,
  qualityTierSchema,
  modelRegistryApprovalStateSchema,
  promptStatusSchema,
  candidateStrategySchema,
  evalStatusSchema,
  evalVerdictSchema,
  testCheckTypeSchema,
  reportStatusSchema,
  reportArtifactFormatSchema,
  reportArtifactPrivacyStateSchema,
  artifactDeletionStatusSchema,
  retentionStateSchema,
  deletionRequestStatusSchema,
  adminActionScopeSchema,
  adminRoleNameSchema,
  adminUserStatusSchema,
  sudoRequestStatusSchema,
  redactionStateSchema,
  accountStageSchema,
  opportunityStageSchema,
  evalReadinessSchema,
  entitlementFeatureSchema,
  usageLedgerUnitSchema,
  ledgerDirectionSchema
} from './common';

export const modelRegistryRecordSchema = z
  .object({
    id: idSchema,
    provider: providerSchema,
    model_id: z.string().min(1),
    display_name: z.string().min(1),
    input_price_per_million_tokens: z.number().nonnegative(),
    output_price_per_million_tokens: z.number().nonnegative(),
    cached_input_price_per_million_tokens: z.number().nonnegative().nullable(),
    context_window: z.number().int().positive(),
    max_output_tokens: z.number().int().positive(),
    supports_text: z.boolean(),
    supports_image: z.boolean(),
    supports_audio: z.boolean(),
    supports_video: z.boolean(),
    supports_tools: z.boolean(),
    supports_structured_output: z.boolean(),
    latency_tier: latencyTierSchema,
    quality_tier: qualityTierSchema,
    recommended_task_types: z.array(taskTypeSchema),
    stability_status: stabilityStatusSchema,
    freshness_status: registryFreshnessSchema,
    source_url: z.string().url().nullable(),
    last_verified_at: isoDateTimeSchema.nullable(),
    verified_by: z.string().min(1).nullable(),
    approval_state: modelRegistryApprovalStateSchema,
    approved_by_admin_user_id: idSchema.nullable(),
    approved_at: isoDateTimeSchema.nullable(),
    pricing_note: z.string().min(1),
    is_mock: z.boolean(),
    metadata: metadataSchema,
    created_at: isoDateTimeSchema,
    updated_at: isoDateTimeSchema
  })
  .strict();
export type ModelRegistryRecord = z.infer<typeof modelRegistryRecordSchema>;

export const modelRegistryVersionSchema = z
  .object({
    id: idSchema,
    model_registry_id: idSchema,
    version_number: z.number().int().positive(),
    registry_payload: metadataSchema,
    source_url: z.string().url(),
    last_verified_at: isoDateTimeSchema.nullable(),
    verified_by: z.string().min(1).nullable(),
    approval_state: modelRegistryApprovalStateSchema,
    approved_by_admin_user_id: idSchema.nullable(),
    approved_at: isoDateTimeSchema.nullable(),
    change_reason: z.string().min(1),
    is_mock: z.boolean(),
    created_at: isoDateTimeSchema
  })
  .strict();
export type ModelRegistryVersion = z.infer<typeof modelRegistryVersionSchema>;
